services:
  model:
    build: 
      dockerfile: ./services/predict/predict.dockerfile
      #image: model:latest
    container_name: python-server
    entrypoint: gunicorn --bind 0.0.0.0:9695 predict_model:app
    ports:
      - 9695:9695
  prep:
    build: 
      dockerfile: ./services/prep/prep.dockerfile
      #image: prep:latest
    container_name: python-prep
    entrypoint: gunicorn --bind 0.0.0.0:9695 predict_prep:app
    ports:
      - 8501:8501
